import assert from "node:assert/strict";
import test from "node:test";

import {
  createCodeTaskPullRequest,
  mergePullRequest,
} from "../src/services/githubWriteService.js";

const repository = "radostinvgeorgiev-commits/sunchron-backend";

test("AI CORE code write creates one atomic tree, commit, branch and pull request", async () => {
  const originalFetch = global.fetch;
  const originalApiUrl = process.env.GITHUB_API_URL;
  const originalRepository = process.env.GITHUB_REPOSITORY;
  const calls = [];
  process.env.GITHUB_API_URL = "https://github.test";
  process.env.GITHUB_REPOSITORY = repository;
  const payloads = [
    { object: { sha: "base-sha" } },
    { tree: { sha: "base-tree" } },
    { sha: "new-tree" },
    { sha: "new-commit" },
    { ref: "refs/heads/ai-core/task-proof" },
    { number: 77, html_url: "https://github.test/pull/77" },
  ];
  global.fetch = async (url, options = {}) => {
    calls.push({ url, options });
    return new Response(JSON.stringify(payloads[calls.length - 1]), {
      status: 200,
    });
  };

  try {
    const result = await createCodeTaskPullRequest({
      repository,
      branchName: "ai-core/task-proof",
      changes: [
        { path: "public/avatar-proof.js", content: "export default true;\n" },
      ],
      commitMessage: "Add avatar proof",
      title: "Add avatar proof",
      body: "Generated by the AI CORE multi-engine council.",
      accessToken: "oauth-token",
    });

    assert.equal(result.commitSha, "new-commit");
    assert.equal(result.pullRequestNumber, 77);
    assert.deepEqual(result.changedFiles, ["public/avatar-proof.js"]);
    assert.equal(calls.length, 6);
    assert.match(calls[2].url, /\/git\/trees$/u);
    assert.match(calls[3].url, /\/git\/commits$/u);
    assert.match(calls[4].url, /\/git\/refs$/u);
    assert.match(calls[5].url, /\/pulls$/u);
    assert.equal(
      JSON.parse(calls[4].options.body).ref,
      "refs/heads/ai-core/task-proof",
    );
  } finally {
    global.fetch = originalFetch;
    if (originalApiUrl === undefined) delete process.env.GITHUB_API_URL;
    else process.env.GITHUB_API_URL = originalApiUrl;
    if (originalRepository === undefined) delete process.env.GITHUB_REPOSITORY;
    else process.env.GITHUB_REPOSITORY = originalRepository;
  }
});

test("AI CORE code write blocks protected deployment files", async () => {
  await assert.rejects(
    () =>
      createCodeTaskPullRequest({
        repository,
        branchName: "ai-core/task-blocked",
        changes: [{ path: ".github/workflows/deploy.yml", content: "unsafe" }],
        commitMessage: "Unsafe",
        title: "Unsafe",
        accessToken: "oauth-token",
      }),
    (error) => error.code === "PROTECTED_PATH",
  );
});

test("confirmed merge binds the exact head SHA and requires green checks", async () => {
  const originalFetch = global.fetch;
  const originalApiUrl = process.env.GITHUB_API_URL;
  const originalRepository = process.env.GITHUB_REPOSITORY;
  const calls = [];
  const headSha = "a".repeat(40);
  const baseSha = "b".repeat(40);
  process.env.GITHUB_API_URL = "https://github.test";
  process.env.GITHUB_REPOSITORY = repository;
  global.fetch = async (url, options = {}) => {
    calls.push({ url, options });
    const payload =
      calls.length === 1
        ? {
            number: 356,
            state: "open",
            merged: false,
            draft: false,
            base: { ref: "main", sha: baseSha },
            head: { ref: "ai-core/task-proof", sha: headSha },
            mergeable: true,
            mergeable_state: "clean",
            html_url: "https://github.test/pull/356",
          }
        : calls.length === 2
          ? { state: "success", total_count: 1 }
          : calls.length === 3
            ? {
                total_count: 1,
                check_runs: [
                  { status: "completed", conclusion: "success" },
                ],
              }
            : {
              sha: "b".repeat(40),
              merged: true,
              message: "Pull Request successfully merged",
            };
    return new Response(JSON.stringify(payload), { status: 200 });
  };

  try {
    const result = await mergePullRequest({
      repository,
      pullNumber: 356,
      expectedHeadSha: headSha,
      expectedBaseSha: baseSha,
      accessToken: "oauth-token",
    });

    assert.equal(result.merged, true);
    assert.equal(result.mergeCommitSha, "b".repeat(40));
    assert.equal(calls.length, 4);
    assert.match(calls[0].url, /\/pulls\/356$/u);
    assert.match(calls[1].url, /\/commits\/aaaaaaaa.*\/status$/u);
    assert.match(calls[2].url, /\/commits\/aaaaaaaa.*\/check-runs$/u);
    assert.match(calls[3].url, /\/pulls\/356\/merge$/u);
    assert.deepEqual(JSON.parse(calls[3].options.body), {
      sha: headSha,
      merge_method: "merge",
    });
  } finally {
    global.fetch = originalFetch;
    if (originalApiUrl === undefined) delete process.env.GITHUB_API_URL;
    else process.env.GITHUB_API_URL = originalApiUrl;
    if (originalRepository === undefined) delete process.env.GITHUB_REPOSITORY;
    else process.env.GITHUB_REPOSITORY = originalRepository;
  }
});

test("confirmed merge stops when CI is not green", async () => {
  const originalFetch = global.fetch;
  const originalApiUrl = process.env.GITHUB_API_URL;
  const originalRepository = process.env.GITHUB_REPOSITORY;
  const headSha = "c".repeat(40);
  process.env.GITHUB_API_URL = "https://github.test";
  process.env.GITHUB_REPOSITORY = repository;
  let mergeCalled = false;
  const baseSha = "d".repeat(40);
  global.fetch = async (url) => {
    if (/\/pulls\/356\/merge$/u.test(url)) mergeCalled = true;
    const payload = /\/status$/u.test(url)
      ? { state: "pending", total_count: 1 }
      : /\/check-runs$/u.test(url)
        ? {
            total_count: 1,
            check_runs: [
              { status: "completed", conclusion: "failure" },
            ],
          }
        : {
          state: "open",
          merged: false,
          base: { ref: "main", sha: baseSha },
          head: { sha: headSha },
          mergeable: true,
          mergeable_state: "clean",
        };
    return new Response(JSON.stringify(payload), { status: 200 });
  };

  try {
    await assert.rejects(
      () =>
        mergePullRequest({
          repository,
          pullNumber: 356,
          expectedHeadSha: headSha,
          expectedBaseSha: baseSha,
          accessToken: "oauth-token",
        }),
      (error) => error.code === "PULL_REQUEST_CHECKS_NOT_GREEN",
    );
    assert.equal(mergeCalled, false);
  } finally {
    global.fetch = originalFetch;
    if (originalApiUrl === undefined) delete process.env.GITHUB_API_URL;
    else process.env.GITHUB_API_URL = originalApiUrl;
    if (originalRepository === undefined) delete process.env.GITHUB_REPOSITORY;
    else process.env.GITHUB_REPOSITORY = originalRepository;
  }
});
