import assert from "node:assert/strict";
import test from "node:test";

import { createCodeTaskPullRequest } from "../src/services/githubWriteService.js";

const repository = "radostinvgeorgiev-commits/sunchron-backend";

test("AI CORE code write creates one atomic tree, commit, branch and pull request", async () => {
  const originalFetch = global.fetch;
  const originalApiUrl = process.env.GITHUB_API_URL;
  const originalRepository = process.env.GITHUB_REPOSITORY;
  const calls = [];
  process.env.GITHUB_API_URL = "https://github.test";
  process.env.GITHUB_REPOSITORY = repository;
  const payloads = [
    { object: { sha: "base-sha" } },
    { tree: { sha: "base-tree" } },
    { sha: "new-tree" },
    { sha: "new-commit" },
    { ref: "refs/heads/ai-core/task-proof" },
    { number: 77, html_url: "https://github.test/pull/77" },
  ];
  global.fetch = async (url, options = {}) => {
    calls.push({ url, options });
    return new Response(JSON.stringify(payloads[calls.length - 1]), {
      status: 200,
    });
  };

  try {
    const result = await createCodeTaskPullRequest({
      repository,
      branchName: "ai-core/task-proof",
      changes: [
        { path: "public/avatar-proof.js", content: "export default true;\n" },
      ],
      commitMessage: "Add avatar proof",
      title: "Add avatar proof",
      body: "Generated by the AI CORE multi-engine council.",
      accessToken: "oauth-token",
    });

    assert.equal(result.commitSha, "new-commit");
    assert.equal(result.pullRequestNumber, 77);
    assert.deepEqual(result.changedFiles, ["public/avatar-proof.js"]);
    assert.equal(calls.length, 6);
    assert.match(calls[2].url, /\/git\/trees$/u);
    assert.match(calls[3].url, /\/git\/commits$/u);
    assert.match(calls[4].url, /\/git\/refs$/u);
    assert.match(calls[5].url, /\/pulls$/u);
    assert.equal(
      JSON.parse(calls[4].options.body).ref,
      "refs/heads/ai-core/task-proof",
    );
  } finally {
    global.fetch = originalFetch;
    if (originalApiUrl === undefined) delete process.env.GITHUB_API_URL;
    else process.env.GITHUB_API_URL = originalApiUrl;
    if (originalRepository === undefined) delete process.env.GITHUB_REPOSITORY;
    else process.env.GITHUB_REPOSITORY = originalRepository;
  }
});

test("AI CORE code write blocks protected deployment files", async () => {
  await assert.rejects(
    () =>
      createCodeTaskPullRequest({
        repository,
        branchName: "ai-core/task-blocked",
        changes: [{ path: ".github/workflows/deploy.yml", content: "unsafe" }],
        commitMessage: "Unsafe",
        title: "Unsafe",
        accessToken: "oauth-token",
      }),
    (error) => error.code === "PROTECTED_PATH",
  );
});
